name: Build and Deploy to AlwaysFree.NET

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish -c Release -o publish

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ${{ secrets.ALF_SERVER }}
        username: ${{ secrets.ALF_USERNAME }}
        password: ${{ secrets.ALF_PASSWORD }}
        local-dir: ./publish
